# Generated by Django 2.0.3 on 2018-11-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='game_detail',
            field=models.ManyToManyField(to='game.GameDetail'),
        ),
    ]
