# Generated by Django 2.0.3 on 2018-12-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_word_game_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='selected_word_id_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='selected_word_id_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='game_detail',
            field=models.ManyToManyField(related_name='words', to='game.GameDetail'),
        ),
    ]
